services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - "3000:3000"
    depends_on:
      - "backend"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    env_file: ".env"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/pokemonteambuilder_data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $PG_USER -d $DB_NAME"]
      interval: 1s
      timeout: 5s
      retries: 10
